Repository PrismJS/prism, pull requests merged in 2018-06, with the labels that each got.

#1255 Added Angular tutorial link
  index.html
Labels: docs, enhancement

#1434 Make line-numbers styles more specific
  plugins/line-numbers/prism-line-numbers.css
Labels: bug

#1435 Add double-class specificity hack
  themes/prism-coy.css
Labels: bug

#1437 Kotlin: add `typealias` keyword
  components/prism-kotlin.js
Labels: enhancement, language-definitions

#1360 Add .token.class-name to rest of themes
  themes/prism-okaidia.css
  themes/prism-solarizedlight.css
Labels: enhancement, themes

#1430 Add TAP component
  components.js
  components.json
  components/prism-tap.js
  components/prism-tap.min.js
  plugins/autoloader/prism-autoloader.js
  plugins/autoloader/prism-autoloader.min.js
  plugins/show-language/prism-show-language.js
  plugins/show-language/prism-show-language.min.js
  tests/languages/tap/bail_out_feature.test
  tests/languages/tap/directive_feature.test
  tests/languages/tap/pass_fail_feature.test
  tests/languages/tap/plan_feature.test
  tests/languages/tap/pragma_feature.test
  tests/languages/tap/version_feature.test
  tests/languages/tap/yamlish_feature.test
Labels: enhancement, language-definitions, needs review

#1440 Fix Swift protocol
  components/prism-swift.js
  components/prism-swift.min.js
  tests/languages/swift/keyword_feature.test
Labels: enhancement, language-definitions, needs review

#1449 Add Python triple-quoted strings "known failure"
  examples/prism-python.html
Labels: bug, docs, language-definitions
