Repository PrismJS/prism, pull requests merged in 2019-01, with the labels that each got.

#1685 Add extension shortcut for Asciidoc
  components.js
  components.json
  components/prism-asciidoc.js
  components/prism-asciidoc.min.js
Labels: enhancement, needs changes

#1620 Add N1QL language support
  components.js
  components.json
  components/prism-n1ql.js
  components/prism-n1ql.min.js
  examples/prism-n1ql.html
  plugins/show-language/prism-show-language.js
  plugins/show-language/prism-show-language.min.js
  tests/languages/n1ql/boolean_feature.test
  tests/languages/n1ql/comment_feature.test
  tests/languages/n1ql/function_feature.test
  tests/languages/n1ql/identifier_feature.test
  tests/languages/n1ql/keyword_feature.test
  tests/languages/n1ql/number_feature.test
  tests/languages/n1ql/operator_feature.test
  tests/languages/n1ql/parameter_feature.test
  tests/languages/n1ql/string_feature.test
Labels: language-definitions, needs changes

#1694 Make false, null and true to be recognized as constants in PHP
  components/prism-php.js
  components/prism-php.min.js
  tests/languages/php/boolean_feature.test
  tests/languages/php/constant_feature.test
  tests/languages/php/keyword_feature.test
Labels: enhancement, language-definitions, needs changes

#1710 Added HDL (Hardware Description Language) support
  components.js
  components.json
  components/prism-hdl.min.js
  components/prism-nand2tetris-hdl.js
  components/prism-nand2tetris-hdl.min.js
  examples/prism-nand2tetris-hdl.html
  plugins/show-language/prism-show-language.js
  plugins/show-language/prism-show-language.min.js
  tests/languages/nand2tetris-hdl/boolean_feature.test
  tests/languages/nand2tetris-hdl/comment_feature.test
  tests/languages/nand2tetris-hdl/function_feature.test
  tests/languages/nand2tetris-hdl/keyword_feature.test
  tests/languages/nand2tetris-hdl/number_feature.test
  tests/languages/nand2tetris-hdl/operator_feature.test
  tests/languages/nand2tetris-hdl/punctuation_feature.test
Labels: language-definitions, needs changes

#1711 Modify attr-name regex to include fields with arguments
  components/prism-graphql.js
  components/prism-graphql.min.js
Labels: enhancement, language-definitions, needs changes

#1702 Removed dead tutorial
  index.html
Labels: website

#1697 C improvements
  components/prism-c.js
  components/prism-c.min.js
  components/prism-cpp.js
  components/prism-cpp.min.js
  components/prism-objectivec.js
  components/prism-objectivec.min.js
  tests/languages/c/class-name_feature.test
  tests/languages/c/keyword_feature.test
  tests/languages/c/number_feature.test
  tests/languages/cpp/class-name_feature.test
  tests/languages/cpp/keyword_feature.test
  tests/languages/opencl/keyword_feature.test
Labels: enhancement, language-definitions, needs review

#1684 GitHub API calls now use the master branch
  download.js
  examples.js
Labels: bug, website

#1674 JSONP Highlight Improvements
  plugins/jsonp-highlight/prism-jsonp-highlight.js
  plugins/jsonp-highlight/prism-jsonp-highlight.min.js
Labels: enhancement, needs review, plugins

#1672 JSONP Highlight: Fixed typos and other small mistakes
  plugins/jsonp-highlight/index.html
Labels: enhancement, plugins, website

#1654 Removed the Prism.tokenize language parameter
  components/prism-core.js
  prism.js
Labels: enhancement

#1683 Show language improvements
  components/prism-java.min.js
  gulpfile.js
  plugins/show-language/prism-show-language.js
  plugins/show-language/prism-show-language.min.js
Labels: enhancement, needs review, plugins

#1709 The `insert-before` hook is now called properly
  components/prism-core.js
  components/prism-core.min.js
  prism.js
Labels: bug, needs review

#1627 Download: No parentheses
  download.html
Labels: enhancement, website

#1603 Decoupled XML from Markup
  components/prism-markup.js
  components/prism-markup.min.js
  prism.js
Labels: enhancement, language-definitions, needs review

#1537 gulp: Inline regex source
  components/prism-pug.js
  components/prism-pug.min.js
  components/prism-pure.js
  components/prism-textile.js
  gulpfile.js
Labels: needs review

#1610 Show invisibles inside tokens
  plugins/show-invisibles/prism-show-invisibles.css
  plugins/show-invisibles/prism-show-invisibles.js
  plugins/show-invisibles/prism-show-invisibles.min.js
Labels: enhancement, needs review, plugins

#1677 Useless `insertBefore` call
  components/prism-smarty.js
  components/prism-smarty.min.js
Labels: enhancement, needs review

#1716 Gulp: Inline ALL regexes
  gulpfile.js
Labels: bug
