Repository PrismJS/prism, pull requests merged in 2019-03, with the labels that each got.

#1784 Added keywords: libname set output options
  components/prism-sas.js
  components/prism-sas.min.js
  tests/languages/sas/keyword_feature.test
Labels: enhancement, language-definitions, needs changes

#1776 Core: VSCode friendly
  components/prism-core.js
  components/prism-core.min.js
  components/prism-sas.min.js
  prism.js
Labels: enhancement, needs review

#1780 gulp: Refactoring
  gulpfile.js
Labels: enhancement, needs review

#1653 Markup-templating improvements
  components/prism-markup-templating.js
  components/prism-markup-templating.min.js
Labels: enhancement, needs review

#1467 Mark operator like functions as functions in scheme
  components/prism-scheme.js
  components/prism-scheme.min.js
  tests/languages/scheme/function_feature.test
Labels: enhancement, language-definitions, needs changes

#1671 CSS: Highlight attribute selector
  components/prism-css-extras.js
  components/prism-css-extras.min.js
  tests/languages/css!+css-extras/selector_attribute_feature.test
  tests/languages/css!+css-extras/selector_feature.test
Labels: enhancement, language-definitions, needs review

#1699 Added T4 Text Templates
  components.js
  components.json
  components/prism-t4-cs.js
  components/prism-t4-cs.min.js
  components/prism-t4-templating.js
  components/prism-t4-templating.min.js
  components/prism-t4-vb.js
  components/prism-t4-vb.min.js
  plugins/autoloader/prism-autoloader.js
  plugins/autoloader/prism-autoloader.min.js
  plugins/show-language/prism-show-language.js
  plugins/show-language/prism-show-language.min.js
  tests/languages/t4-cs/block_class-feature_feature.test
  tests/languages/t4-cs/block_directive_feature.test
  tests/languages/t4-cs/block_expression_feature.test
  tests/languages/t4-cs/block_standard_feature.test
  tests/languages/t4-vb/block_feature.test
Labels: language-definitions, needs review, new langauge

#1660 Markup: Added support for CSS and JS inside of CDATAs
  components/prism-css.js
  components/prism-css.min.js
  components/prism-javascript.js
  components/prism-javascript.min.js
  components/prism-markup.js
  components/prism-markup.min.js
  prism.js
  tests/languages/markup!+css+javascript/issue1240.test
  tests/languages/markup!+css/css_inclusion.test
  tests/languages/markup!+javascript/javascript_inclusion.test
  tests/languages/markup+javascript+csharp+aspnet/script_feature.test
Labels: bug, language-definitions, needs review

#1682 Regex language
  components.js
  components.json
  components/prism-regex.js
  components/prism-regex.min.js
  tests/languages/javascript!+regex/regex_inclusion.test
  tests/languages/regex/anchor_feature.test
  tests/languages/regex/backreference_feature.test
  tests/languages/regex/charclass_feature.test
  tests/languages/regex/charset_feature.test
  tests/languages/regex/escape_feature.test
  tests/languages/regex/group_feature.test
  tests/languages/regex/quantifier_feature.test
  tests/languages/regex/range_feature.test
Labels: language-definitions, needs review, new langauge

#1768 Ruby/ERB: Fixed block comments
  components/prism-erb.js
  components/prism-erb.min.js
  components/prism-ruby.js
  components/prism-ruby.min.js
  tests/languages/erb/issue1767.test
  tests/languages/ruby/comment_feature.test
Labels: bug, language-definitions, needs review

#1759 Fixed dependencies of Pug and Pure
  components.js
  components.json
  components/prism-pug.js
  components/prism-pug.min.js
  components/prism-pure.js
  components/prism-pure.min.js
  plugins/autoloader/prism-autoloader.js
  plugins/autoloader/prism-autoloader.min.js
Labels: language-definitions

#1769 EJS language
  components.js
  components.json
  components/prism-ejs.js
  components/prism-ejs.min.js
  examples/prism-ejs.html
  plugins/autoloader/prism-autoloader.js
  plugins/autoloader/prism-autoloader.min.js
  plugins/show-language/prism-show-language.js
  plugins/show-language/prism-show-language.min.js
  tests/languages/ejs/comment_feature.test
  tests/languages/ejs/ejs_feature.test
Labels: language-definitions, needs review, new langauge

#1791 Coy: Fixed line drift issue in Edge
  themes/prism-coy.css
  themes/prism-dark.css
  themes/prism-funky.css
  themes/prism-okaidia.css
  themes/prism-solarizedlight.css
  themes/prism-tomorrow.css
  themes/prism-twilight.css
  themes/prism.css
Labels: bug, needs review, themes

#1638 CSS: Selectors can contain any string
  components/prism-css.js
  components/prism-css.min.js
  prism.js
  tests/languages/css/selector_feature.test
Labels: enhancement, language-definitions, needs review

#1772 Better class name detection
  plugins/line-numbers/prism-line-numbers.js
  plugins/line-numbers/prism-line-numbers.min.js
  plugins/normalize-whitespace/prism-normalize-whitespace.js
  plugins/normalize-whitespace/prism-normalize-whitespace.min.js
  plugins/remove-initial-line-feed/prism-remove-initial-line-feed.js
  plugins/remove-initial-line-feed/prism-remove-initial-line-feed.min.js
Labels: enhancement, needs review, plugins

#1775 Fixed patterns which can match the empty string
  components/prism-fsharp.js
  components/prism-fsharp.min.js
  components/prism-hpkp.js
  components/prism-hpkp.min.js
  components/prism-hsts.js
  components/prism-hsts.min.js
  components/prism-twig.js
  components/prism-twig.min.js
Labels: enhancement, language-definitions, needs review

#1771 Markdown: The 'md' alias is now recognized
  components/prism-markdown.js
  components/prism-markdown.min.js
Labels: bug, enhancement, language-definitions, needs review

#1742 Npm: Fixed mocha and gulp-uglify vulnerabilities
  package.json
Labels: enhancement, needs consensus

#1793 JSONP highlight: Fixed minified adapter names
  plugins/jsonp-highlight/prism-jsonp-highlight.js
  plugins/jsonp-highlight/prism-jsonp-highlight.min.js
Labels: bug, needs review, plugins

#1788 GraphQL improvements
  components/prism-graphql.js
  components/prism-graphql.min.js
  tests/languages/graphql/attr-name_feature.test
  tests/languages/graphql/class-name_feature.test
  tests/languages/graphql/constant_feature.test
  tests/languages/graphql/fragment_feature.test
  tests/languages/graphql/keyword_feature.test
  tests/languages/graphql/operator_feature.test
Labels: enhancement, language-definitions, needs review

#1798 Markup: `addInline` improvements
  components/prism-markup.js
  components/prism-markup.min.js
  prism.js
  tests/languages/markup!+css/css_inclusion.test
  tests/languages/markup!+javascript/javascript_inclusion.test
Labels: enhancement, language-definitions, needs review

#1800 Django/Jinja2 improvements
  components.js
  components.json
  components/prism-django.js
  components/prism-django.min.js
  plugins/autoloader/prism-autoloader.js
  plugins/autoloader/prism-autoloader.min.js
  tests/languages/django!+css/inclusion.test
  tests/languages/django!+javascript/inclusion.test
  tests/languages/django/boolean_feature.test
  tests/languages/django/comment_feature.test
  tests/languages/django/delimiter_feature.test
  tests/languages/django/filter_feature.test
  tests/languages/django/for-loop_feature.test
  tests/languages/django/function_feature.test
  tests/languages/django/keyword_feature.test
  tests/languages/django/property_feature.test
  tests/languages/django/tag_feature.test
  tests/languages/django/test_feature.test
  tests/languages/django/variable_feature.test
Labels: enhancement, language-definitions, needs review

#1801 Tests: Pretty-printed token stream
  test-suite.html
  tests/helper/test-case.js
  tests/helper/token-stream-transformer.js
  tests/run.js
Labels: enhancement, needs review

#1799 Line numbers: Inheritance for the `line-numbers` class
  plugins/line-numbers/index.html
  plugins/line-numbers/prism-line-numbers.js
  plugins/line-numbers/prism-line-numbers.min.js
Labels: enhancement, needs review, plugins

#1760 Some encouragement for visitors of PrismJS.com to request new languages
  index.html
Labels: enhancement, needs consensus, website

#1757 Test page: Show tokens option
  test.html
Labels: enhancement, website

#1795 Tests: Refactoring
  tests/helper/prism-loader.js
  tests/helper/test-case.js
  tests/helper/test-discovery.js
  tests/helper/token-stream-transformer.js
  tests/run.js
  tests/testrunner-tests.js
Labels: enhancement

#1774 Docs: Added missing `Prism.highlight` parameter
  extending.html
Labels: docs, enhancement

#1650 CSS extras: Highlighting for pseudo class arguments
  components/prism-css-extras.js
  components/prism-css-extras.min.js
  tests/languages/css!+css-extras/selector_feature.test
  tests/languages/css!+css-extras/selector_n-th_feature.test
  tests/languages/css!+css-extras/selector_pseudo-class_feature.test
Labels: enhancement, language-definitions, needs review

#1489 More variables for better code compression
  components/prism-asciidoc.js
  components/prism-asciidoc.min.js
  components/prism-parser.js
  components/prism-parser.min.js
  components/prism-plsql.js
  components/prism-plsql.min.js
  components/prism-powershell.js
  components/prism-powershell.min.js
  components/prism-textile.js
  components/prism-textile.min.js
Labels: enhancement, language-definitions, needs review

#1529 More persistent test page
  test.html
Labels: enhancement, website

#1781 Website: Added script directory
  download.html
  examples.html
  extending.html
  faq.html
  index.html
  plugins/autolinker/index.html
  plugins/autoloader/index.html
  plugins/command-line/index.html
  plugins/copy-to-clipboard/index.html
  plugins/custom-class/index.html
  plugins/data-uri-highlight/index.html
  plugins/file-highlight/index.html
  plugins/highlight-keywords/index.html
  plugins/index.html
  plugins/jsonp-highlight/index.html
  plugins/keep-markup/index.html
  plugins/line-highlight/index.html
  plugins/line-numbers/index.html
  plugins/normalize-whitespace/index.html
  plugins/previewers/index.html
  plugins/remove-initial-line-feed/index.html
  plugins/show-invisibles/index.html
  plugins/show-language/index.html
  plugins/toolbar/index.html
  plugins/unescaped-markup/index.html
  plugins/wpd/index.html
  scripts/code.js
  scripts/download.js
  scripts/examples.js
  scripts/prefixfree.min.js
  scripts/utopia.js
  scripts/vendor/FileSaver.min.js
  scripts/vendor/jszip.min.js
  scripts/vendor/promise.js
  test-suite.html
  test.html
Labels: enhancement, needs consensus, website

#1646 Adds unit tests to the Keep Markup plugin
  package.json
  plugins/keep-markup/prism-keep-markup.js
  plugins/keep-markup/prism-keep-markup.min.js
  tests/plugins/keep-markup/test.js
Labels: accepted, enhancement, needs changes

#1804 Applied Array.isArray
  components/prism-core.js
  components/prism-core.min.js
  components/prism-flow.js
  components/prism-flow.min.js
  components/prism-javadoclike.js
  components/prism-javadoclike.min.js
  components/prism-plsql.js
  components/prism-plsql.min.js
  plugins/autolinker/prism-autolinker.js
  plugins/autolinker/prism-autolinker.min.js
  plugins/data-uri-highlight/prism-data-uri-highlight.js
  plugins/data-uri-highlight/prism-data-uri-highlight.min.js
  plugins/keep-markup/prism-keep-markup.min.js
  plugins/previewers/prism-previewers.js
  plugins/previewers/prism-previewers.min.js
  prism.js
  scripts/download.js
  scripts/examples.js
Labels: enhancement, needs review

#1809 npm: Fixed `test` script
  package.json
  test-suite.html
Labels: bug, needs review

#1820 Adding initial support for CMake language
  components.js
  components.json
  components/prism-cmake.js
  components/prism-cmake.min.js
  examples/prism-cmake.html
  plugins/show-language/prism-show-language.js
  plugins/show-language/prism-show-language.min.js
  tests/languages/cmake/boolean_feature.test
  tests/languages/cmake/comment_feature.test
  tests/languages/cmake/function_feature.test
  tests/languages/cmake/inserted_feature.test
  tests/languages/cmake/keyword_feature.test
  tests/languages/cmake/namespace_feature.test
  tests/languages/cmake/number_feature.test
  tests/languages/cmake/operator_feature.test
  tests/languages/cmake/property_feature.test
  tests/languages/cmake/punctuation_feature.test
  tests/languages/cmake/string_feature.test
  tests/languages/cmake/variable_feature.test
Labels: language-definitions, needs changes, new langauge

#1823 Apache config: Minor improvements + new keyword
  components/prism-apacheconf.js
  components/prism-apacheconf.min.js
  tests/languages/apacheconf/directive-inline_feature.test
Labels: enhancement, language-definitions, needs review

#1831 Haskell: Added `hs` alias
  components.js
  components.json
  components/prism-haskell.js
  components/prism-haskell.min.js
  plugins/show-language/prism-show-language.js
  plugins/show-language/prism-show-language.min.js
Labels: enhancement, needs review

#1811 Fixed download page
  download.html
  scripts/download.js
Labels: bug, needs review, website

#1828 Autoloader: Fixed the directory of scripts
  plugins/autoloader/index.html
Labels: bug, needs review, plugins

#1830 Added missing aliases
  components.js
  components.json
  plugins/show-language/prism-show-language.js
  plugins/show-language/prism-show-language.min.js
Labels: enhancement, needs review

#1829 Autoloader: Added support for aliases
  gulpfile.js
  plugins/autoloader/index.html
  plugins/autoloader/prism-autoloader.js
  plugins/autoloader/prism-autoloader.min.js
Labels: enhancement, needs review, plugins

#1832 Added alias tests
  components.js
  components.json
  package.json
  plugins/autoloader/prism-autoloader.js
  plugins/autoloader/prism-autoloader.min.js
  plugins/show-language/prism-show-language.js
  plugins/show-language/prism-show-language.min.js
  tests/aliases-test.js
Labels: enhancement, needs review

#1814 Scheme: Minor improvements
  components/prism-scheme.js
  components/prism-scheme.min.js
  tests/languages/scheme/character_feature.test
  tests/languages/scheme/string_feature.test
Labels: enhancement, language-definitions, needs review

#1818 Toolbar: Minor improvements
  plugins/toolbar/index.html
  plugins/toolbar/prism-toolbar.js
  plugins/toolbar/prism-toolbar.min.js
Labels: enhancement, needs review, plugins

#1834 Adjusted .npmignore
  .npmignore
Labels: enhancement, needs review

#1803 Tests: Additional checks for Prism functions
  tests/checks/extend.js
  tests/checks/insert-before.js
  tests/helper/check-functionality.js
  tests/helper/prism-loader.js
Labels: enhancement, needs review

#1819 Travis: Fail when changed files are detected
  .travis.yml
  components/prism-markdown.min.js
  gulpfile.js
  package-lock.json
  package.json
  plugins/autoloader/prism-autoloader.min.js
  plugins/previewers/prism-previewers.min.js
Labels: enhancement, needs review

#1837 Core: Removed `parent` from `wrap`'s environment
  components/prism-core.js
  components/prism-core.min.js
  prism.js
Labels: enhancement, needs review

#1850 Clearer description for the highlighting bug report template
  .github/ISSUE_TEMPLATE/highlighting-bug-report.md
Labels: enhancement, needs review
