Repository PrismJS/prism, pull requests merged in 2019-06, with the labels that each got.

#1925 Docs: Creating a new language definition
  extending.html
Labels: enhancement, needs review, website

#1899 C#: Added `cs` alias
  components.js
  components.json
  components/prism-csharp.js
  components/prism-csharp.min.js
  plugins/autoloader/prism-autoloader.js
  plugins/autoloader/prism-autoloader.min.js
  plugins/show-language/prism-show-language.js
  plugins/show-language/prism-show-language.min.js
Labels: enhancement, language-definitions, needs review

#1890 Tests: Expanded regex tests
  components/prism-elixir.js
  components/prism-elixir.min.js
  components/prism-tt2.js
  components/prism-tt2.min.js
  tests/regex-tests.js
Labels: enhancement, needs review

#1908 Test page: use Core instead of prism.js
  test.html
Labels: enhancement, needs review, website

#1896 Added support for JQ
  components.js
  components.json
  components/prism-jq.js
  components/prism-jq.min.js
  examples/prism-jq.html
  plugins/show-language/prism-show-language.js
  plugins/show-language/prism-show-language.min.js
  tests/languages/jq/boolean_feature.test
  tests/languages/jq/comment_feature.test
  tests/languages/jq/dot_feature.test
  tests/languages/jq/function_feature.test
  tests/languages/jq/keyword_feature.test
  tests/languages/jq/operator_feature.test
  tests/languages/jq/property_feature.test
  tests/languages/jq/punctuation_feature.test
  tests/languages/jq/string_feature.test
  tests/languages/jq/variable_feature.test
Labels: language-definitions, needs review, new language

#1933 gulp: JSON formatting for partly generated files
  gulpfile.js
  plugins/autoloader/prism-autoloader.js
  plugins/show-language/prism-show-language.js
Labels: enhancement, needs review

#1443 Bash improvements
  components/prism-bash.js
  components/prism-bash.min.js
  tests/languages/bash/arithmetic_environment_feature.test
  tests/languages/bash/assign-left_feature.test
  tests/languages/bash/builtin_feature.test
  tests/languages/bash/command_substitution_feature.test
  tests/languages/bash/comment_feature.test
  tests/languages/bash/entities_in_strings_feature.test
  tests/languages/bash/environment_feature.test
  tests/languages/bash/for-or-select_feature.test
  tests/languages/bash/function-name_feature.test
  tests/languages/bash/function_feature.test
  tests/languages/bash/keyword_feature.test
  tests/languages/bash/operator_feature.test
  tests/languages/bash/shebang_feature.test
  tests/languages/bash/string_feature.test
  tests/languages/bash/variable_feature.test
Labels: enhancement, language-definitions, needs changes

#1938 SCSS: Fixed exp time failing of url pattern
  components/prism-scss.js
  components/prism-scss.min.js
Labels: enhancement, language-definitions, needs review

#1917 Added some examples
  components/prism-toml.js
  components/prism-toml.min.js
  examples/prism-javadoc.html
  examples/prism-jsdoc.html
  examples/prism-phpdoc.html
  examples/prism-t4-cs.html
  examples/prism-t4-vb.html
  examples/prism-toml.html
  tests/languages/toml/table_feature.test
Labels: enhancement, language-definitions, needs review, website

#1916 LaTeX: Added support for $$ equations
  components/prism-latex.js
  components/prism-latex.min.js
  tests/languages/latex/equation_feature.test
Labels: enhancement, language-definitions, needs review

#1892 Added shell session language
  components.js
  components.json
  components/prism-bash.js
  components/prism-shell-session.js
  components/prism-shell-session.min.js
  examples/prism-shell-session.html
  plugins/autoloader/prism-autoloader.js
  plugins/autoloader/prism-autoloader.min.js
  plugins/show-language/prism-show-language.js
  plugins/show-language/prism-show-language.min.js
  tests/languages/scss/atrule_feature.test
  tests/languages/shell-session/command_feature.test
  tests/languages/shell-session/command_string_feature.test
Labels: language-definitions, needs review, new language

#1943 Add `return` to recognised Perl keywords
  components/prism-perl.js
  components/prism-perl.min.js
  tests/languages/perl/keyword_feature.test
Labels: enhancement, language-definitions, needs review

#1897 Markdown: Added support for nested bold and italic tokens
  components/prism-markdown.js
  components/prism-markdown.min.js
  tests/languages/markdown/bold_feature.test
  tests/languages/markdown/italic_feature.test
  tests/languages/markdown/nested_bold_italic_feature.test
  tests/languages/markdown/strike_feature.test
Labels: enhancement, language-definitions, needs review

#1920 Download page: Fixed Edge's word wrap
  download.html
Labels: enhancement, needs review, website

#1951 Add className option for toolbar items
  plugins/toolbar/prism-toolbar.js
  plugins/toolbar/prism-toolbar.min.js
Labels: enhancement, needs changes, plugins

#1952 Website: Updated page styles to not interfere with themes
  style.css
Labels: enhancement, needs review, website

#1949 Extending page: Fixed typo + new alias section
  extending.html
Labels: docs, enhancement, needs review, website

#1935 Autoloader: Fixed and improved callbacks
  plugins/autoloader/prism-autoloader.js
  plugins/autoloader/prism-autoloader.min.js
Labels: bug, enhancement, needs review, plugins

#1934 README: Added npm downloads badge
  README.md
Labels: enhancement, needs review

#1924 Website: Added basic usage for CDNs
  index.html
Labels: enhancement, needs review, website

#1919 Examples improvements
  scripts/examples.js
Labels: enhancement, needs review, website
