Repository PrismJS/prism, pull requests merged in 2020-12, with the labels that each got.

#2664 Add CSP and UISecurity directives and keywords
  components/prism-csp.js
  components/prism-csp.min.js
  tests/languages/csp/directive_with_source_expression_feature.test
  tests/languages/csp/safe_feature.test
  tests/languages/csp/unsafe_feature.test
Labels: enhancement, language-definitions, needs changes

#2670 Remove the icon from README.md
  README.md
  docs/index.html
Labels: enhancement, needs changes

#2638 Fixed Danger CI for forks
  .github/workflows/danger.yml
  dangerfile.js
Labels: bug, needs review

#2631 Treeview: Fixed icons on dark themes
  .npmignore
  bower.json
  gulpfile.js/changelog.js
  gulpfile.js/index.js
  package-lock.json
  package.json
  plugins/treeview/icons/archive.svg
  plugins/treeview/icons/audio.svg
  plugins/treeview/icons/code.svg
  plugins/treeview/icons/excel.svg
  plugins/treeview/icons/file.svg
  plugins/treeview/icons/folder.svg
  plugins/treeview/icons/image.svg
  plugins/treeview/icons/pdf.svg
  plugins/treeview/icons/powerpoint.svg
  plugins/treeview/icons/text.svg
  plugins/treeview/icons/video.svg
  plugins/treeview/icons/word.svg
  plugins/treeview/prism-treeview.css
Labels: enhancement, needs review, plugins

#2572 Tests: Added strict checks for `Prism.languages.extend`
  components/prism-arduino.js
  components/prism-arduino.min.js
  components/prism-birb.js
  components/prism-birb.min.js
  components/prism-c.js
  components/prism-c.min.js
  components/prism-d.js
  components/prism-d.min.js
  components/prism-gml.js
  components/prism-gml.min.js
  components/prism-go.js
  components/prism-go.min.js
  components/prism-javascript.js
  components/prism-javascript.min.js
  components/prism-jolie.js
  components/prism-jolie.min.js
  components/prism-objectivec.js
  components/prism-objectivec.min.js
  components/prism-opencl.js
  components/prism-opencl.min.js
  components/prism-qore.js
  components/prism-qore.min.js
  components/prism-scala.js
  components/prism-scala.min.js
  components/prism-sparql.js
  components/prism-sparql.min.js
  components/prism-sqf.js
  components/prism-sqf.min.js
  components/prism-vala.js
  components/prism-vala.min.js
  components/prism-vbnet.js
  components/prism-vbnet.min.js
  prism.js
  tests/helper/checks.js
Labels: enhancement, language-definitions, needs review

#2491 New start script to start local server
  package-lock.json
  package.json
Labels: enhancement, needs review

#2575 Test page: Added share option
  .github/ISSUE_TEMPLATE/highlighting-bug-report.md
  test.html
Labels: enhancement, needs review, website

#2677 Test page: Don't trigger ad-blockers with class
  test.html
Labels: enhancement, needs review, website

#2678 Markdown: Improved URL tokenization
  components/prism-markdown.js
  components/prism-markdown.min.js
  tests/languages/markdown/bold_feature.test
  tests/languages/markdown/italic_feature.test
  tests/languages/markdown/strike_feature.test
  tests/languages/markdown/url_feature.test
Labels: enhancement, language-definitions, needs review

#2237 Line highlight: Fixed top offset in combination with Line numbers
  plugins/line-highlight/index.html
  plugins/line-highlight/prism-line-highlight.js
  plugins/line-highlight/prism-line-highlight.min.js
Labels: enhancement, needs review, plugins

#2668 Line Highlight: Fixed print background color
  plugins/line-highlight/prism-line-highlight.css
Labels: enhancement, needs review, plugins

#2680 C-like: Made all comments greedy
  components/prism-clike.js
  components/prism-clike.min.js
  components/prism-coffeescript.js
  components/prism-coffeescript.min.js
  prism.js
  tests/languages/coffeescript/inline-javascript_feature.test
Labels: bug, language-definitions, needs review

#2682 Latte: Fixed exponential backtracking
  components/prism-latte.js
  components/prism-latte.min.js
Labels: enhancement, language-definitions

#2684 PHP: Fixed exponential backtracking
  components/prism-php.js
  components/prism-php.min.js
Labels: enhancement, language-definitions
