Repository PrismJS/prism, pull requests merged in 2021-05, with the labels that each got.

#2861 TypeScript: Updated keywords
  components/prism-typescript.js
  components/prism-typescript.min.js
  tests/languages/typescript/issue2860.test
  tests/languages/typescript/keyword_feature.test
Labels: enhancement, language-definitions, needs review

#2864 PHP: Fixed string interpolation
  components/prism-php.js
  components/prism-php.min.js
  tests/languages/php/string-interpolation_feature.test
Labels: enhancement, language-definitions, needs review

#2870 ESLint: Re-enable no-cond-assign rule
  .eslintrc.js
  components/prism-core.js
  docs/prism-core.js.html
  plugins/diff-highlight/prism-diff-highlight.js
  plugins/file-highlight/prism-file-highlight.js
  plugins/filter-highlight-all/prism-filter-highlight-all.js
  plugins/jsonp-highlight/prism-jsonp-highlight.js
  plugins/previewers/prism-previewers.js
  prism.js
Labels: enhancement, needs review

#2863 ESLint: Added no-tabs rule
  .eslintrc.js
  components/prism-bro.js
  components/prism-dataweave.js
Labels: enhancement, needs review

#2869 ESLint: Added JSDoc plugin
  .eslintrc.js
  components/prism-core.js
  components/prism-kumir.js
  dependencies.js
  docs/global.html
  docs/prism-core.js.html
  package-lock.json
  package.json
  plugins/line-numbers/prism-line-numbers.js
  plugins/previewers/prism-previewers.js
  prism.js
  tests/helper/test-discovery.js
  tests/identifier-test.js
Labels: enhancement, needs review

#2862 ESLint: Added spacing rules
  .eslintrc.js
  assets/code.js
  assets/download.js
  assets/examples.js
  components/prism-abap.js
  components/prism-actionscript.js
  components/prism-bash.js
  components/prism-bro.js
  components/prism-coffeescript.js
  components/prism-core.js
  components/prism-crystal.js
  components/prism-dart.js
  components/prism-dataweave.js
  components/prism-ejs.js
  components/prism-elixir.js
  components/prism-erb.js
  components/prism-factor.js
  components/prism-groovy.js
  components/prism-haml.js
  components/prism-handlebars.js
  components/prism-inform7.js
  components/prism-ini.js
  components/prism-io.js
  components/prism-jolie.js
  components/prism-jsx.js
  components/prism-latte.js
  components/prism-llvm.js
  components/prism-mongodb.js
  components/prism-n4js.js
  components/prism-pug.js
  components/prism-pure.js
  components/prism-qsharp.js
  components/prism-renpy.js
  components/prism-sass.js
  components/prism-smarty.js
  components/prism-solution-file.js
  components/prism-tt2.js
  components/prism-typoscript.js
  components/prism-v.js
  components/prism-vala.js
  components/prism-xeora.js
  docs/prism-core.js.html
  plugins/autolinker/prism-autolinker.js
  plugins/copy-to-clipboard/prism-copy-to-clipboard.js
  plugins/highlight-keywords/prism-highlight-keywords.js
  plugins/keep-markup/prism-keep-markup.js
  plugins/normalize-whitespace/prism-normalize-whitespace.js
  plugins/previewers/prism-previewers.js
  plugins/remove-initial-line-feed/prism-remove-initial-line-feed.js
  plugins/toolbar/prism-toolbar.js
  plugins/wpd/prism-wpd.js
  prism.js
  tests/pattern-tests.js
  tests/plugins/keep-markup/test.js
Labels: enhancement, needs review

#2829 Website: Moved vendor files into `vendor` folder
  .eslintrc.js
  assets/vendor/prefixfree.min.js
  assets/vendor/utopia.js
  download.html
  examples.html
  extending.html
  faq.html
  index.html
  known-failures.html
  plugins/autolinker/index.html
  plugins/autoloader/index.html
  plugins/command-line/index.html
  plugins/copy-to-clipboard/index.html
  plugins/custom-class/index.html
  plugins/data-uri-highlight/index.html
  plugins/diff-highlight/index.html
  plugins/download-button/index.html
  plugins/file-highlight/index.html
  plugins/filter-highlight-all/index.html
  plugins/highlight-keywords/index.html
  plugins/index.html
  plugins/inline-color/index.html
  plugins/jsonp-highlight/index.html
  plugins/keep-markup/index.html
  plugins/line-highlight/index.html
  plugins/line-numbers/index.html
  plugins/match-braces/index.html
  plugins/normalize-whitespace/index.html
  plugins/previewers/index.html
  plugins/remove-initial-line-feed/index.html
  plugins/show-invisibles/index.html
  plugins/show-language/index.html
  plugins/toolbar/index.html
  plugins/treeview/index.html
  plugins/unescaped-markup/index.html
  plugins/wpd/index.html
  test-suite.html
  test.html
Labels: enhancement, needs review, website

#2688 Tests: Exhaustive pattern tests
  components/prism-erb.js
  components/prism-erb.min.js
  tests/pattern-tests.js
Labels: enhancement, needs review

#2886 Tests: Test discovery should ignore unsupported file extensions
  tests/helper/test-discovery.js
Labels: bug

#2872 Shell sessions: Fixed multi-line commands
  components/prism-shell-session.js
  components/prism-shell-session.min.js
  tests/languages/shell-session/issue2871.test
Labels: enhancement, language-definitions, needs review

#2874 Handlebars: Added `hbs` alias
  components.js
  components.json
  components/prism-handlebars.js
  components/prism-handlebars.min.js
  plugins/autoloader/prism-autoloader.js
  plugins/autoloader/prism-autoloader.min.js
  plugins/show-language/prism-show-language.js
  plugins/show-language/prism-show-language.min.js
Labels: enhancement, language-definitions, needs review

#2891 Tests: Fixed polynomial backtracking test
  tests/helper/util.js
Labels: bug

#2881 ESLint: Added indent rule
  .eslintrc.js
  assets/code.js
  assets/download.js
  assets/examples.js
  components/prism-bro.js
  components/prism-coffeescript.js
  components/prism-core.js
  components/prism-crystal.js
  components/prism-dataweave.js
  components/prism-dax.js
  components/prism-jsx.js
  components/prism-nsis.js
  components/prism-powerquery.js
  docs/prism-core.js.html
  plugins/autolinker/prism-autolinker.js
  plugins/diff-highlight/prism-diff-highlight.js
  plugins/highlight-keywords/prism-highlight-keywords.js
  plugins/line-highlight/prism-line-highlight.js
  plugins/normalize-whitespace/prism-normalize-whitespace.js
  plugins/previewers/prism-previewers.js
  plugins/remove-initial-line-feed/prism-remove-initial-line-feed.js
  plugins/toolbar/prism-toolbar.js
  plugins/wpd/prism-wpd.js
  prism.js
Labels: enhancement, needs review

#2885 Ruby: Add heredoc literals
  components/prism-ruby.js
  components/prism-ruby.min.js
  examples/prism-ruby.html
  tests/languages/ruby/string_feature.test
Labels: enhancement, language-definitions, needs changes

#2906 Replace my.cdn in code sample with example.com
  index.html
Labels: enhancement, needs changes, website

#2889 PHP: Fixed functions with namespaces
  components/prism-php.js
  components/prism-php.min.js
  tests/languages/latte/delimiter_feature.test
  tests/languages/php!+css-extras/issue2008.test
  tests/languages/php!+php-extras/scope_feature.test
  tests/languages/php/argument-name_feature.test
  tests/languages/php/class-name_feature.test
  tests/languages/php/function_feature.test
  tests/languages/php/string-interpolation_feature.test
Labels: enhancement, language-definitions, needs review

#2888 CI: Run tests with NodeJS 16.x
  .github/workflows/test.yml
Labels: enhancement, needs review

#2899 Readme: Mention `npm ci`
  README.md
  docs/index.html
Labels: docs, enhancement, needs review

#2896 Command Line: Don't modify empty code blocks
  plugins/command-line/prism-command-line.js
  plugins/command-line/prism-command-line.min.js
Labels: enhancement, needs review, plugins

#2900 JS: Added support for RegExp Match Indices
  components/prism-javascript.js
  components/prism-javascript.min.js
  prism.js
  tests/languages/javascript/regex_feature.test
Labels: enhancement, language-definitions, needs review

#2901 ESLint: Added curly rule
  .eslintrc.js
  assets/code.js
  assets/download.js
  components/prism-markup-templating.js
  dangerfile.js
  plugins/normalize-whitespace/prism-normalize-whitespace.js
  tests/helper/test-case.js
Labels: enhancement, needs review

#2902 ESLint: Added eol-last rule
  .eslintrc.js
  components/prism-abap.js
  components/prism-ada.js
  components/prism-arff.js
  components/prism-bbcode.js
  components/prism-brainfuck.js
  components/prism-csp.js
  components/prism-dot.js
  components/prism-haxe.js
  components/prism-icon.js
  components/prism-keyman.js
  components/prism-mizar.js
  components/prism-neon.js
  components/prism-nim.js
  components/prism-php-extras.js
  components/prism-powerquery.js
  components/prism-soy.js
  components/prism-stylus.js
  components/prism-v.js
  components/prism-wasm.js
  components/prism-xojo.js
  tests/helper/util.js
  tests/languages/asciidoc/entity_feature.js
  tests/languages/groovy/string-interpolation_feature.js
Labels: enhancement, needs review

#2923 Deps: Updated regex tooling
  package-lock.json
  package.json
  tests/pattern-tests.js
Labels: dependencies, enhancement
