Repository PrismJS/prism, pull requests merged in 2021-04, with the labels that each got.

#2842 AQL: Update for ArangoDB 3.8
  components/prism-aql.js
  components/prism-aql.min.js
  tests/languages/aql/keyword_feature.test
  tests/languages/aql/number_feature.test
Labels: enhancement, language-definitions

#2809 Tests: Added --insert and --update
  test-suite.html
  tests/helper/test-case.js
  tests/helper/token-stream-transformer.js
  tests/run.js
Labels: enhancement, needs review

#2826 Copy to Clipboard: iFrame fix
  plugins/copy-to-clipboard/prism-copy-to-clipboard.js
  plugins/copy-to-clipboard/prism-copy-to-clipboard.min.js
Labels: bug, needs review, plugins

#2820 TypeScript: Added support for decorators
  components/prism-typescript.js
  components/prism-typescript.min.js
  tests/languages/typescript/decorator_feature.test
  tests/languages/typescript/issue2819.test
Labels: enhancement, language-definitions, needs review

#2818 PHP: Fixed methods with keyword names + minor improvements
  components/prism-php.js
  components/prism-php.min.js
  tests/languages/php/attribute_feature.test
  tests/languages/php/class-name_feature.test
  tests/languages/php/delimiter_feature.test
  tests/languages/php/function_feature.test
  tests/languages/php/keyword_feature.test
  tests/languages/php/type_feature.test
Labels: enhancement, language-definitions, needs review

#2814 C++: Added generic functions and made `::` punctuation
  components/prism-cpp.js
  components/prism-cpp.min.js
  tests/languages/cpp/base-clause_feature.test
  tests/languages/cpp/class-name_feature.test
  tests/languages/cpp/function_feature.test
  tests/languages/cpp/issue2347.test
  tests/languages/cpp/operator_feature.test
  tests/languages/cpp/punctuation_feature.test
Labels: enhancement, language-definitions, needs review

#2821 Tests: Fixed pretty print incorrectly calculating print width
  tests/helper/token-stream-transformer.js
Labels: enhancement, needs review

#2812 Java: Improved generics
  components/prism-java.js
  components/prism-java.min.js
  tests/languages/java/generics_feature.test
Labels: enhancement, language-definitions, needs review

#2841 Ruby: Added missing regex interpolation
  components/prism-ruby.js
  components/prism-ruby.min.js
  tests/languages/ruby/regex_feature.test
Labels: enhancement, language-definitions, needs review

#2846 ESLint: Added `root` to config to prevent warning
  .eslintrc.js
Labels: enhancement

#2845 Ruby: Added missing regex flags
  components/prism-ruby.js
  components/prism-ruby.min.js
  tests/languages/ruby/regex_feature.test
Labels: enhancement, language-definitions, needs review

#2847 ESLint: Fail CI if there are warnings
  .github/workflows/test.yml
  package.json
Labels: enhancement, needs review

#2835 ESLint: Added quotes rule
  .eslintrc.js
  assets/code.js
  assets/download.js
  assets/examples.js
  components/prism-abap.js
  components/prism-aspnet.js
  components/prism-autoit.js
  components/prism-bash.js
  components/prism-diff.js
  components/prism-jexl.js
  components/prism-kotlin.js
  components/prism-less.js
  components/prism-naniscript.js
  components/prism-pascaligo.js
  components/prism-peoplecode.js
  components/prism-smarty.js
  components/prism-vbnet.js
  components/prism-xeora.js
  components/prism-xquery.js
  dangerfile.js
  dependencies.js
  gulpfile.js/changelog.js
  gulpfile.js/docs.js
  gulpfile.js/index.js
  gulpfile.js/paths.js
  plugins/autoloader/prism-autoloader.js
  plugins/command-line/prism-command-line.js
  plugins/copy-to-clipboard/prism-copy-to-clipboard.js
  plugins/highlight-keywords/prism-highlight-keywords.js
  plugins/jsonp-highlight/prism-jsonp-highlight.js
  plugins/normalize-whitespace/prism-normalize-whitespace.js
  plugins/show-language/prism-show-language.js
  tests/aliases-test.js
  tests/core/greedy.js
  tests/dependencies-test.js
  tests/helper/checks.js
  tests/helper/prism-loader.js
  tests/helper/test-case.js
  tests/helper/test-discovery.js
  tests/helper/token-stream-transformer.js
  tests/identifier-test.js
  tests/pattern-tests.js
  tests/plugins/keep-markup/test.js
  tests/run.js
  tests/testrunner-tests.js
Labels: enhancement, needs review

#2836 ESLint: Added semi rule
  .eslintrc.js
  assets/code.js
  assets/download.js
  assets/examples.js
  components/prism-cil.js
  components/prism-cpp.js
  components/prism-csharp.js
  components/prism-dns-zone-file.js
  components/prism-haml.js
  components/prism-icu-message-format.js
  components/prism-ignore.js
  components/prism-javadoc.js
  components/prism-jq.js
  components/prism-json5.js
  components/prism-jsstacktrace.js
  components/prism-jsx.js
  components/prism-markdown.js
  components/prism-nevod.js
  components/prism-powerquery.js
  components/prism-pug.js
  components/prism-qsharp.js
  components/prism-regex.js
  components/prism-splunk-spl.js
  components/prism-xquery.js
  components/prism-yaml.js
  dangerfile.js
  gulpfile.js/changelog.js
  gulpfile.js/docs.js
  plugins/autoloader/prism-autoloader.js
  plugins/copy-to-clipboard/prism-copy-to-clipboard.js
  plugins/custom-class/prism-custom-class.js
  plugins/file-highlight/prism-file-highlight.js
  plugins/line-highlight/prism-line-highlight.js
  plugins/normalize-whitespace/prism-normalize-whitespace.js
  plugins/wpd/prism-wpd.js
  prism.js
  tests/dependencies-test.js
  tests/examples-test.js
  tests/helper/checks.js
  tests/helper/test-case.js
  tests/helper/token-stream-transformer.js
  tests/plugins/keep-markup/test.js
Labels: enhancement, needs review

#2837 ESLint: Added no-var rule
  .eslintrc.js
  gulpfile.js/docs.js
  tests/aliases-test.js
  tests/helper/checks.js
Labels: enhancement, needs review

#2851 small regex changes for better generic log support
  components/prism-log.js
  components/prism-log.min.js
Labels: enhancement, language-definitions, needs changes

#2867 ESLint: Added wrap-iife rule
  .eslintrc.js
  assets/code.js
  assets/download.js
  components/prism-abnf.js
  components/prism-apex.js
  components/prism-bash.js
  components/prism-core.js
  components/prism-css-extras.js
  components/prism-django.js
  components/prism-factor.js
  components/prism-latex.js
  components/prism-naniscript.js
  components/prism-promql.js
  components/prism-scheme.js
  components/prism-v.js
  docs/prism-core.js.html
  plugins/autolinker/prism-autolinker.js
  plugins/copy-to-clipboard/prism-copy-to-clipboard.js
  plugins/custom-class/prism-custom-class.js
  plugins/download-button/prism-download-button.js
  plugins/file-highlight/prism-file-highlight.js
  plugins/highlight-keywords/prism-highlight-keywords.js
  plugins/jsonp-highlight/prism-jsonp-highlight.js
  plugins/line-highlight/prism-line-highlight.js
  plugins/show-invisibles/prism-show-invisibles.js
  plugins/show-language/prism-show-language.js
  plugins/toolbar/prism-toolbar.js
  plugins/wpd/prism-wpd.js
  prism.js
  tests/run.js
Labels: enhancement, needs review

#2865 ESLint: Added brace-style rule
  .eslintrc.js
  assets/code.js
  assets/download.js
  components/prism-core.js
  docs/Prism.hooks.html
  docs/Prism.html
  docs/Token.html
  docs/global.html
  docs/prism-core.js.html
  plugins/autolinker/prism-autolinker.js
  plugins/data-uri-highlight/prism-data-uri-highlight.js
  plugins/jsonp-highlight/prism-jsonp-highlight.js
  plugins/wpd/prism-wpd.js
  prism.js
Labels: enhancement, needs review

#2866 ESLint: Added no-use-before-define rule
  .eslintrc.js
  gulpfile.js/changelog.js
  plugins/line-highlight/prism-line-highlight.js
  plugins/line-numbers/prism-line-numbers.js
  plugins/line-numbers/prism-line-numbers.min.js
Labels: enhancement, needs review
